Austin-Jack/asclepius-vue

接口说明文档.md
=> docs:add api documentation

vue.config.js
=> fix:fixed vue.config error

src/main.js, src/pages/scheduling.vue, vue.config.js
=> feat: init scheduling

接口说明文档.md
=> docs:add api docs /getCards

src/pages/scheduling.vue, src/router.js
=> feat: finish data simulation first

src/components/PatientCard.vue, src/pages/appointment.vue
=> feat:finish appointment style

接口说明文档.md
=> docs:underscore variable name to camel case

src/components/PatientCard.vue, src/pages/AppointDetail.vue
=> feat:finish the steps of adding patientCard

src/components/NavHeader.vue, src/dist/router.dev.js, src/pages/scheduling.vue, src/pages/userCenter.vue, src/router.js
=> feat: refactoring scheduling

.gitignore, 接口说明文档.md
=> docs:add description of authentication failure

src/components/PatientCard.vue, src/mock/api.js, src/pages/AppointDetail.vue, src/pages/appointment.vue
=> feat:added the mock of add patientCard

src/components/NavHeader.vue, src/mock/api.js, src/pages/AppointDetail.vue, src/pages/appointment.vue, src/router.js
=> feat:added the loading of departments based by level

src/mock/api.js, src/pages/AppointDetail.vue, src/pages/appointment.vue, src/router.js
=> feat:finish the test of appointmentDetail

src/mock/api.js, src/pages/AppointDetail.vue
=> refactor:modify the getting of doctor schedule

src/components/NavHeader.vue
=> fix: fix NavHeader

src/dist/router.dev.js, src/mock/api.js, src/mock/dist/api.dev.js, src/pages/userCenter.vue, vue.config.js
=> feat:finsh userCenter static

src/mock/api.js, src/pages/AppointDetail.vue, src/pages/appointment.vue
=> fix:the receicing of data

src/dist/main.dev.js, src/main.js, src/mock/api.js, src/mock/dist/api.dev.js, src/pages/scheduling.vue, src/pages/userCenter.vue, vue.config.js
=> feat:finally finish scheduling interface

src/pages/appointment.vue
=> feat:added page dividing

src/mock/api.js, src/mock/dist/api.dev.js, src/pages/scheduling.vue, src/pages/userCenter.vue, vue.config.js
=> fix:scheduling async await

.gitignore, deploy.sh, src/mock/api.js
=> chore:add deploy shell

babel.config.js, package-lock.json, package.json, src/components/PatientCard.vue, src/dist/main.dev.js, src/main.js, src/mock/api.js, src/mock/dist/api.dev.js, src/pages/AppointDetail.vue, src/pages/appointment.vue, src/pages/userCenter.vue
=> perf: element-ui lazyload

deploy.sh, src/pages/appointment.vue
=> fix:fixup doctors level' correspondence

src/components/PatientCard.vue, src/pages/AppointDetail.vue, src/pages/appointment.vue, src/pages/docDetail.vue, src/pages/userCenter.vue, vue.config.js
=> fix:the verifaction of token

src/dist/main.dev.js, src/dist/router.dev.js, src/main.js, src/pages/home.vue, src/pages/login.vue, src/pages/userCenter.vue, src/router.js, vue.config.js
=> feat: perfect function

src/App.vue, src/components/PatientCard.vue, src/mock/api.js, src/pages/AppointDetail.vue, src/pages/appointment.vue, src/pages/docDetail.vue, src/router.js
=> add the code of appoinment

src/pages/login.vue, src/pages/userCenter.vue
=> feat: add paganation

src/pages/scheduling.vue, vue.config.js
=> refactor: scheduling responsive

src/dist/router.dev.js, src/pages/login.vue, src/router.js
=> fix: login bug

src/components/NavHeader.vue, src/dist/router.dev.js, src/router.js
=> fix:login 403 bug

src/pages/AppointDetail.vue
=> feat:add back
